name = "Equilibrium_Galactica"
uid = "86d439dd-2532-43b4-b87b-7052f7de4ca6"
version = 2
copyright = "Ithilis - feel free to use this code, but ask permission first, and credit me in your mod"
description = "Equilibrium balance with all strange stuff that go on Ithilis mind!"
icon = "/mods/Equilibrium_balance_mod/Equilibrium_balance_mod.png"
author = "Ithilis"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
